export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';

export const RECEIVED_FIREBASE_DATA = 'RECEIVED_FIREBASE_DATA';
export const SHOW_GUIDELINE = 'SHOW_GUIDELINE';
export const SHOW_LIST = 'SHOW_LIST';
